url: https://bharathksunil.github.io
# baseurl: 

# Site settings
title: Bharath Kumar S
email: bharathk.sunil.k@gmail.com
description: "I am a Results-driven &amp; tenacious professional with an entrepreneurial spirit offering high calibre strengths in building &amp; driving superior operation success &amp; strategic planning. Posses a robust background in Android App development with compliance to best coding standards. Resilient &amp; organised with well-anchored problem solving skills coupled with extraordinary attention to detail &amp; the willingness to go above &amp; beyond the job description. Hire Me Now."

intro-lead: Hello, Welcome.!
intro-heading: It's Nice To Meet You...
intro-button: Know About Me

# These are the sections in your page---NOTE: Remember, this is kept here for easy editing
section1: About
section1-subhead: Let Me Give you a Brief Introducion about Myself
section1-id: about

section2: Education
section2-subhead: "\"Education Is Not The Learning of Facts, But The Training of Minds to Think\" - <i>Albert Einstein</i>"
section2-id: education

section3: Projects
section3-subhead: My Projects Can Best Describe My Skills
section3-id: projects

section4: Hobbies
section4-subhead: Here Are Some Of Things I Love Doing When I Relax
section4-id: hobbies

section5: Achievements
section5-subhead: Here Are Some Achievements I Have Earned
section5-id: achievements

section6: Contact Me
section6-subhead: Loved it? Hire Me.! or Feel Free To Contact Me With Any Feedback or Queries
section6-id: contact


# Mention the name of the hobby, a short description and the font-awesome icon tag
hobbies:
- name: Coding
  description: "That feelng of Accomplishment mixed with Exictement I experience when I have sucessfully Compiled &amp; Run the code I just wrote &amp; debugged is Addictive."
  icon: code
- name: Pencil Sketching
  description: "Inclination towards sketching began since I was small, I have contributed my art to many magazines &amp; display boards at school."
  icon: "pencil-square-o"
- name: Gaming
  description: "I Got to play on a PC when I was in 3<sup>rd</sup> or 4<sup>th</sup> Std. <br/>I started playing games like Dave, Aladdin, Pac-Man &amp; slowly moved to NFS Most wanted then GTA Vice City &amp; now Playing Batman, GTA V &amp; Clash Of Clans."
  icon: gamepad
- name: Cooking
  description: "I Love Food.! &amp; I always love to pamper myself with great food &amp; Its best to cook it ourself to stay healthy. I started cooking when I was young. I cook a variety of food from Indian to Chineese to Italian."
  icon: cutlery
- name: Dancing
  description: "I had a transition from fear of performing on stage to many Dance Performances &amp; a few Choreographs. I can dance Hip-Hop, Contemporary &amp; Break-Dance."
  icon: music
- name: Many More
  description: "I do a lot more than I can mention here. So, lets meet &amp; talk about it ;p"
  icon: list

# Team names, titles and social links
people:
- name: Bharath Kumar S
  pic: "img/about/1.jpg"
  position: Android Developer
  social:
    - title: twitter
      url: "http://www.twitter.com/bharathksunil"
    - title: facebook
      url: "http://www.facebook.com/bharathksunil"
    - title: cloud
      url: "https://trailhead.salesforce.com/en/me/bharathksunil"
    - title: instagram
      url: "http://www.instagram.com/the._.developer"
    - title: github
      url: "http://github.com/bharathksunil"
    - title: quora
      url: "http://www.quora.com/bharath-kumar-s-9"
    - title: linkedin
      url: "https://in.linkedin.com/in/bharathksunil"
    - title: play
      url: "https://play.google.com/store/apps/dev?id=6734202426383547966&hl=en"
  description: "Hello There..! I am Bharath Kumar S from Bengaluru, India. My father is an Officer in the Indian Air Force &amp; that explains why I have done my schooling in various Kendriya Vidyalaya's across India. Its also why I can Socialize &amp; Acclimatize very fast. I try to be Organised, Happy &amp; Simple.<br /><br />I am also a self-taught <b>Android Developer</b> with over a year of experience in developing Android Applications. <b>I have deployed 2 of my apps in the Google Play Store</b>. My first app is a Expenditure management app with <b>over 500 downloads &amp; 4.8 Rating by 82 users.</b> I am currently working on 3 different projects; <br /><b>WalkSafe:</b> A Woman Safety mobile application<br /><b>UBuyQuick-Vendor:</b> A vendor application for a bangalore startup.<br /><b>Salesforce Helper:</b> A java based application to help me track performance of students on Trailhead. <br /> <br />I have experience with working on Android Framework, Java, SQL, NoSQL, Firebase, PHP &amp; currently learning cloud on AWS and Salesforce. I love to play games &amp; volleyball is my favourite outdoor game followed by cricket &amp; football. I am very passionate about technology &amp; am always excited to read &amp; know about them."

# Social networks usernames (many more available: http://fontawesome.io/cheatsheet/)
social:
  - title: twitter
    url: "http://www.twitter.com/bharathksunil"
  - title: facebook
    url: "http://www.facebook.com/bharathksunil"
  - title: instagram
    url: "http://www.instagram.com/the._.developer"

# Build settings
markdown: kramdown
permalink: pretty
