url: https://bharathksunil.github.io
# baseurl: /agency-jekyll-theme/

# Site settings
title: Bharath Kumar S
email: bharathk.sunil.k@gmail.com
description: "Results-driven and tenacious professional with an entrepreneurial spirit offering high calibre strengths in building and driving superior operation success and strategic planning. Posses a robust background in Android App development with compliance to best coding standards. Resilient and organised with well-anchored problem solving skills coupled with extraordinary attention to detail and the willingness to go above and beyond the job description."


# Team names, titles and social links

- name: Bharath Kumar S
  pic: 1
  position: Android Developer
  social:
    - title: twitter
      url: http://www.twitter.com/bharathksunil
    - title: facebook
      url: http://www.facebook.com/bharathk.sunil.k
    - title: cloud
      url: https://trailhead.salesforce.com/en/me/bharathksunil
    - title: instagram
      url: http://www.instagram.com/the._.developer
    - title: github
      url: http://github.com/bharathksunil
    - title: quora
      url: http://www.quora.com/bharath-kumar-s-9
    - title: linkedin
      url: https://in.linkedin.com\in\bharath-kumar-s-1427b810b
    - title: play
      url: https://play.google.com\store\apps\dev?id=6734202426383547966&hl=en

# Social networks usernames (many more available: http://fontawesome.io/cheatsheet/)
social:
  - title: twitter
    url: http://www.twitter.com/bharathksunil
  - title: facebook
    url: http://www.facebook.com/bharathk.sunil.k
  - title: cloud
    url: https://trailhead.salesforce.com/en/me/bharathksunil
  - title: instagram
    url: http://www.instagram.com/the._.developer
  - title: github
    url: http://github.com/bharathksunil
  - title: quora
    url: http://www.quora.com/bharath-kumar-s-9
  - title: linkedin
    url: in.linkedin.com\in\bharath-kumar-s-1427b810b
  - title: play
    url: play.google.com\store\apps\dev?id=6734202426383547966&hl=en
    
# Postal address (add as many lines as necessary)
address:
  - line: p. 166/8 Golden Jubilee Complex
  - line: Air Force Officers Enclave, Arillery Road
  - line: Agram P.O., Bengaluru - 560007
  - line: Karnataka, India 

# Build settings
markdown: kramdown
permalink: pretty